accounts/urls.py
from django.urls import path 
from accounts.views import signup, user_login

app_name = "accounts"
urlpatterns = [
    path("signup/", signup, name = "signup"),
    path("login/" user_login, name = "user_login"),
]

recipes/urls.py
from django.urls import path
from recipes.views import recipe_list, show_recipe, create_recipe, edit_recipe

app_name = "recipes"
urlpatterns = [
    path("recipes/<int:id>/", show_recipe, name="show_recipe"),
    path("recipes/", recipe_list, name="list_recipe"),
    path("recipes/create/", create_recipe, name = "create_recipe"),
    path("recipes/<int:pk>/edit", edit_recipe, name = "edit_recipe"),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect 

def redirect_to_recipe_list (request):
    return redirect("recipe_list")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipes.urls")),
    path("accounts/", include("accounts.urls"))
   
]

accounts/models.py
from django.db import models

# Create your models here.

recipes/models.py
from django.db import models

# Create your models here.
class Recipe(models.Model):
    title = models.CharField(max_length =200)
    picture = models.URLField()
    description = models.TextField()
    created_on = models.DateTimeField(auto_now_add = True)
    author = models.CharField(max_length= 150, default= "User Name")

accounts/forms.py
from django import forms


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=150)
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)
    password_confirmation = forms.CharField(max_length=150, widget=forms.PasswordInput)

class LogInForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)

recipes/forms.py
from django import forms
from recipes.models import Recipe

class RecipeForm(forms.ModelForm):
    email_address = forms.EmailField(max_length=300)

    class Meta:
        model = Recipe
        fields = [
            "title",
            "picture",
            "description",
        ]

accounts/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from accounts.forms import LogInForm, SignUpForm

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username'] 
            password = form.cleaned_data['password']
            password_confirmation = form.cleaned_data ['password_confirmation']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']

            if password == password_confirmation:
             user = User.objects.create_user(
                 username,
                 password = password,
                 first_name = first_name,
                 last_name = last_name,
             )

             login(request, user)
             return redirect("recipes:list_recipe")
        else:
            form.add_error("password", "Passwords do not match")
    else:
        form = SignUpForm()
    context ={
        "form": form
    }
    return render(request, "accounts/signup.html", context)


def user_login(request):
    if request.method == "POST":
        form = LogInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(
                request, 
                username = username,
                password = password,
            )

            if user is not None:
                login(request, user)
                return redirect('recipes:list_recipe')
        else:
            form = LogInForm()
        context = {
            "form" : form,
        }
        return render(request,"accounts/login.html", context)

recipes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from recipes.forms import RecipeForm
from recipes.models import Recipe 

# Create your views here.
def show_recipe(request, id):
    recipe = get_object_or_404(Recipe, id =id)
    context = {
        "recipe" :recipe,
    }
    return render(request, "recipes/detail.html", context)


def recipe_list(request):
    recipes = Recipe.objects.all()
    context = {
        "recipe_list":recipes,
    }
    return render(request, "recipes/list.html", context)


def create_recipe(request):
    if request.method == "POST":
        form = RecipeForm (request.POST)
        if form.is_valid():
            form.save()
            return redirect("list_recipe")
    else:
        form = RecipeForm()

    context ={
        "form":form,
    }

    return render(request, "recipes/create.html", context)

def edit_recipe(request, pk):
    recipe = get_object_or_404(Recipe, id=pk)
    if request.method == "POST":
        form = RecipeForm(request.POST, instance=recipe)
        if form.is_valid():
            return redirect("show_recipe", id=pk)

    else:
        form = RecipeForm(instance=recipe)

    context ={
        "recipe":recipe,
        "recipe_form": form,
    }
    return render(request, "recipes/edit.html", context)

accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
    {% endblock title %}
  </title>
  <link rel="stylesheet" href="{% static 'css/recipes.css' %}">
</head>
<body>
  {% block content %}
  {% endblock content %}
  <footer>
    Made with love by Scrumptious Recipes
  </footer>
</body>
</html>

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
Login!- Scrumptious Recipes
{% endblock title %} 

{% block content %} 
<header>
    <nav>
        <a href="{% url 'recipes:list_recipe' %}">Main Page</a>
    </nav>
</header>
<main>
    <h1>Login!</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Submit</button>
    </form>
</main>
{% endblock content %} 

accounts/templates/accounts/signup.html
{% extends 'accounts/base.html' %} 

{% block title %}
Sign Up! - Scrumptious Recipes
{% endblock title %}

{% block content %}

<header>
  <nav>
    <a href="{% url 'recipes:list_recipe' %}">Main page</a>
  </nav>
</header>

<main>
  <h1>Sign up!</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Sign up</button>
  </form>
</main>

{% endblock content %}
</body>
</html>

recipes/templates/recipes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
    {% endblock title %}
  </title>
  <link rel="stylesheet" href="{% static 'css/recipes.css' %}">
</head>
<body>
  {% block content %}
  {% endblock content %}
  <footer>
    Made with love by Scrumptious Recipes
  </footer>
</body>
</html>

recipes/templates/recipes/create.html
{% extends 'recipes/base.html' %} 

{% block title %} 
    Scrumptious Recipes
{% endblock title %} 

{% block content %} 
<header>
    <nav>
      <a href="{% url 'list_recipe' %}">Main page</a>
    </nav>
  </header>
  <main>
  <form method ="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Create</button>
  </form>
  </main>

{% endblock content %}

recipes/templates/recipes/detail.html
{% extends 'recipes/base.html' %} 

{% block title %}
  Scrumptious Recipes
{% endblock title %}

{% block content %}
<header>
  <nav>
    <a href="{% url 'list_recipe' %}">Main page</a>
   
  </nav>
</header>
<main>
  <h1>Scrumptious Recipes</h1>
  <h2>All the food that's fit to eat</h2>
  <div class="recipe-grid">
    <div>
      <h3>
        <a href="{% url 'edit_recipe' recipe.id %}">Edit Recipe</a>
      </h3>
      <img src="https://mks.io/public-tacos">
      <div>4.3 stars</div>
    </div>
  </div>
</main>

{% endblock content %}

recipes/templates/recipes/edit.html
{% extends 'recipes/base.html' %}

{% block title %}
    Scrumptious Recipes
{% endblock title %} 

{% block content %}
<header>
    <nav>
      <a href="{% url 'list_recipe' %}">Main page</a>
    </nav>
  </header>
  <main>
    <h1>Edit{{ recipe.title }}</h1>
  <form method ="post">
    {% csrf_token %}
    {{ recipe_form.as_p }}
    <button>Save</button>
  </form>
  </main>
{% endblock content %}

recipes/templates/recipes/list.html
{% extends 'recipes/base.html' %}

{% block title %}
    Scrumptious Recipes
{% endblock title %}

{% block content %}
<header>
    <nav>
      <a href="{% url 'recipes:list_recipe' %}">Main page</a>
      <a href="{% url 'recipes:create_recipe' %}">Create a recipe</a>
    
    {% if user.is_authenticated %}
        Hello, {{user.username}}
    {% else %}
      <a href="{% url 'accounts:signup' %}">Sign Up</a>
      <a href="{%url 'accounts:user_login' %}">LogIn</a>
      {% endif %}
    </nav>
  </header>
  <main>
    <h1>Scrumptious Recipes</h1>
    <h2>All the food that's fit to eat</h2>
    <div class="recipe-grid">
        {% for recipe in recipe_list %}
      <div>
        <h3>
            <a href="{% url 'recipes:show_recipe' recipe.id %}">{{ recipe.title }}</a>
          <p>{{ recipe.created_on|date:"M d, Y"}}</p>
        </h3>
        <img src="{{recipe.picture}}">
        <div>4.3 stars</div>
        {% endfor %}
      </div>
    </div>
  </main>
{% endblock content %}